version: '3.2'
services:
  geth:
    image: "matterlabs/geth:latest"
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
    - type: bind
      source: ./volumes/geth
      target: /var/lib/geth/data
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  contract-verifier:
    image: "matterlabs/contract-verifier:latest"
    ports:
      - "3070:3070"
    volumes:
      - type: bind
        source: ./volumes/contract-verifier
        target: /var/lib/contract-verifier/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./etc/env/docker.env
