[package]
name = "zksync_external_node"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/cronos-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_core = { path = "../zksync_core", version = "1.0" }
zksync_dal = { path = "../../lib/dal", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }
zksync_eth_client = { path = "../../lib/eth_client", version = "1.0" }
zksync_basic_types = { path = "../../lib/basic_types", version = "1.0" }
prometheus_exporter = { path = "../../lib/prometheus_exporter", version = "1.0" }
zksync_health_check = { path = "../../lib/health_check", version = "0.1.0" }
vlog = { path = "../../lib/vlog", version = "1.0" }

anyhow = "1.0"
tokio = { version = "1", features = ["time"] }
